### ISSUE TITLE
Load tracking results in Pose estimation

### ISSUE THREAD

**Issue by edwardnguyen1705** [riips/AIC24_Track1_YACHIYO_RIIPS#4]
Dear @riips ,

Thanks for sharing one of your great work.

Regarding the pose estimation step, I see this line

https://github.com/riips/AIC24_Track1_YACHIYO_RIIPS/blob/f881fe0edf60fe697efb2bf4c935b80a80861230/poser/top_down_video_demo_with_track_file.py#L98

However, at this step, both single cam and multiple cam tracking have not been executed yet, so could you please tell me what is about and how to obtain that file?

Thank you so much for your time.

**Comment by edwardnguyen1705** [comment]
Dear @riips ,

I know that the `track_result` is actually detection result. Now, I am able to run your code with my videos.

**Comment by OnceUponATimeMathley** [comment]
> Dear [@riips](https://github.com/riips) ,
> 
> I know that the `track_result` is actually detection result. Now, I am able to run your code with my videos.

Could you please share the password for this dataset with me? Thank you.
I tried requesting it but have not received a response from the NVIDIA AI Challenge team.
I would like to reproduce the results from one of the top teams.
If possible, please share it via my email: [longchauhl@gmail.com](mailto:longchauhl@gmail.com).
Thanks again!
